language: node_js
node_js:
  - "node"
before_script:
  - npm install -g tiddlywiki
script: ./build.sh
deploy:
  provider: pages
  local_dir: garden/output/static
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
